on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  rustfmt:
    name: Rust Format
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo fmt --all -- --check

  test_nightly_std:
    name: Nightly tests std
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main

  test_nightly_no_std:
    name: Nightly tests no_std
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --no-default-features 
